language: node_js

node_js:
  - node

jobs:
    include:
        - stage: install
          script:
            - npm ci

        - stage: build
          script:
            - npm run build --if-present
    
        - stage: lint
          script:
            # - npm install eslint
            # - npm run lint
        
        - stage: unit test
          script:
            - npm run test

        - stage: publish
        #   if: branch = master
          services:
            - docker
          script:
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - docker build -t tci-multirepo-public-backend .
            - docker tag tci-multirepo-public-backend $REPO:travis-$TRAVIS_BUILD_NUMBER
            - docker push $REPO